### PR TITLE
Add tegra lib stubs and remove unused nvjpeg requirement

### PR DESCRIPTION
**Pull request by madsciencetist**
NVIDIA does not distribute the jetson multimedia libraries other than on Jetson board images, so the only way to link against these libs is to compile directly on a Jetson, making it difficult to create automated builds or Docker images. This commit adds stubs of those libraries so that nvmpi and ffmpeg can be built without them. The real libraries will still be required at runtime.

Stubs generated using [so-stub](https://github.com/jackyf/so-stub). They are neither static, rpathed nor installed so that there is no chance of them overriding the real libraries. If someone were to LD_LIBRARY_PATH or manually copy the stubs into an existing library path, the stubbed functions will print an error message and `abort()` when called.

### CODE REVIEW

**Comment by madsciencetist** [comment]
Example dockerizable build script:
```bash
#!/bin/bash

set -euxo pipefail

apt-get -qq install -y --no-install-recommends build-essential clang cmake pkg-config

# Install libnvmpi to enable nvmpi decoders (h264_nvmpi, hevc_nvmpi)
if [ -e /usr/local/cuda-10.2 ]; then
    # assume Jetpack 4.X
    wget -q https://developer.nvidia.com/embedded/L4T/r32_Release_v5.0/T186/Jetson_Multimedia_API_R32.5.0_aarch64.tbz2 -O jetson_multimedia_api.tbz2
else
    # assume Jetpack 5.X
    wget -q https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v3.1/release/jetson_multimedia_api_r35.3.1_aarch64.tbz2 -O jetson_multimedia_api.tbz2
fi
tar xaf jetson_multimedia_api.tbz2 -C / && rm jetson_multimedia_api.tbz2

wget -q https://github.com/Keylost/jetson-ffmpeg/archive/refs/heads/master.zip
unzip master.zip && rm master.zip && cd jetson-ffmpeg-master
build
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j$(nproc)
make install
cd ../
LD_LIBRARY_PATH=$(pwd)/stubs:$LD_LIBRARY_PATH   # tegra multimedia libs aren't available in image, so use stubs for ffmpeg 
cd ../

# Install nv-codec-headers to to enable ffnvcodec filters (scale_cuda)
wget -q https://github.com/FFmpeg/nv-codec-headers/archive/refs/heads/master.zip
unzip master.zip && rm master.zip && cd nv-codec-headers-master
make install
cd ../ && rm -rf nv-codec-headers-master

# Build ffmpeg with nvmpi patch
wget -q https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
tar xaf ffmpeg-*.tar.xz && rm ffmpeg-*.tar.xz && cd ffmpeg-*
patch -p1 < ../jetson-ffmpeg-master/ffmpeg_patches/ffmpeg6.0_nvmpi.patch
# enable Jetson codecs but disable dGPU codecs
./configure --enable-nvmpi --enable-ffnvcodec --enable-cuda-llvm --disable-cuvid --disable-nvenc --disable-nvdec
make -j$(nproc)
make install
cd ../
```

**Comment by madsciencetist** [comment]
Hah, I had removed nvjpeg because the stub was empty! Added it back.

I tried your `NvFaultEx`, replicated the segfault without nvjpeg and the lack of segfault with it, and then verified that it remains fixed when linking against an empty nvjpeg stub.

So this should be good now

**Comment by madsciencetist** [comment]
Wait, not yet :-(

**Comment by madsciencetist** [comment]
Docker build works on latest master with both Jetpack 4.6 and Jetpack 5.0

**Comment by Keylost** [comment]
I added several cmake options to make it more convenient to write automated build scripts and accepted stubs into the master branch. :)
Now you can do something like this:

    cmake -DWITH_STUBS=ON -DJETSON_MULTIMEDIA_API_DIR=/home/user/build_deps/jetson_multimedia_api ..
    make

See readme for details.

**Pull request merged**
